apiVersion: "tekton.dev/v1"
kind: "PipelineRun"
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: "0.60.x"
    tekton.dev/displayName: "Such a job will not work as the [*] \"notation\" with\
      \ array param is not supported in a task's script"
    tekton.dev/platforms: "linux/amd64"
  labels:
    app.kubernetes.io/version: "0.1"
  name: "basic-job-3"
spec:
  pipelineSpec:
    tasks:
    - name: "say-hello"
      params:
      - name: "name"
        value: "team"
      - name: "value"
        value: "Aurea"
      taskSpec:
        steps:
        - image: "registry.access.redhat.com/ubi9@sha256:1ee4d8c50d14d9c9e9229d9a039d793fcbc9aa803806d194c957a397cf1d2b17"
          name: "run-script"
          script: |-
            #!/usr/bin/env bash

            members=($(params.team[*]))

            for member in "${members[@]}"; do
              echo "Say hello to: $member"
            done
  timeouts:
    pipeline: "300000000000ns"
