apiVersion: "tekton.dev/v1"
kind: "PipelineRun"
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: "0.60.x"
    tekton.dev/displayName: "Basic job echoing a message"
    tekton.dev/platforms: "linux/amd64"
  labels:
    app.kubernetes.io/version: "0.1"
  name: "basic-job-1"
spec:
  pipelineSpec:
    tasks:
    - name: "say-hello"
      taskSpec:
        steps:
        - image: "ubuntu"
          name: "run-script"
          script: |-
            #!/usr/bin/env bash

            echo "Say hello to the team"
  timeouts:
    pipeline: "300000000000ns"
