apiVersion: "tekton.dev/v1"
kind: "PipelineRun"
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: "0.60.x"
    tekton.dev/displayName: "Basic job echoing a message using the param teamMember"
    tekton.dev/platforms: "linux/amd64"
  labels:
    app.kubernetes.io/version: "0.1"
  name: "basic-job-2"
spec:
  pipelineSpec:
    tasks:
    - name: "say-hello"
      params:
      - name: "name"
        value: "teamMember"
      - name: "value"
        value: "Aurea"
      taskSpec:
        stepTemplate: {}
        steps:
        - image: "registry.access.redhat.com/ubi9@sha256:1ee4d8c50d14d9c9e9229d9a039d793fcbc9aa803806d194c957a397cf1d2b17"
          name: "run-script"
          script: |-
            #!/usr/bin/env bash

            echo $(params.teamMember)
  timeouts:
    pipeline: "300000000000ns"
