# Buildpacks parameters
- name: APP_IMAGE
  value: $(params.output-image)  #${IMAGE_NAME}
- name: SOURCE_SUBPATH
  value: $(params.sourceSubPath)
- name: CNB_BUILDER_IMAGE
  value: $(params.cnbBuilderImage) #${BUILDER_IMAGE}
- name: CNB_LIFECYCLE_IMAGE
  value: $(params.cnbLifecycleImage) #${LIFECYCLE_IMAGE}
- name: CNB_EXPERIMENTAL_MODE
  value: $(params.cnbExperimentalMode)
- name: CNB_LOG_LEVEL
  value: $(params.cnbLogLevel)
- name: CNB_RUN_IMAGE
  value: $(params.cnbRunImage) #${CNB_RUN_IMAGE}
- name: CNB_BUILD_IMAGE
  value: $(params.cnbBuildImage) #${CNB_BUILD_IMAGE}
- name: CNB_USER_ID
  value: $(tasks.buildpacks-extension-check.results.uid)
- name: CNB_GROUP_ID
  value: $(tasks.buildpacks-extension-check.results.gid)
- name: CNB_ENV_VARS
  value: ["$(params.cnbBuildEnvVars)"]