# The flavor will be used to render the pipeline according to a specific provider: konflux, tekton
flavor: konflux

pipeline:
  # The domain allows to organize the resources, tasks to be used
  domain: buildpack
  name: pipeline-konflux # name of the pipeline to be created
  # The builder corresponds to the following buildpacks concept:
  builder:
    repository:
      name: https://github.com/paketo-community/builder-ubi-base
      branch: main
    #task:
    #  name:
    #  params:

