---
apiVersion: "tekton.dev/v1"
kind: "Task"
metadata:
  annotations:
    tekton.dev/categories: "Image build"
    tekton.dev/displayName: "pack builder"
    tekton.dev/pipelines.minVersion: "0.50.0"
    tekton.dev/platforms: "linux/amd64"
    tekton.dev/tags: "image-build"
  labels:
    app.kubernetes.io/version: "0.1"
  name: "pack-builder"
spec:
  description: "pack client building the builder image - https://buildpacks.io/docs/tools/pack/cli/pack_builder/"
  params:
  - default: "false"
    description: "Enable experimental features"
    name: "PACK_EXPERIMENTAL"
    type: "string"
  - default: "buildpacksio/pack"
    description: "The image to use for the pack client."
    name: "PACK_CLI_IMAGE"
    type: "string"
  - default: "latest"
    description: "Pack client version"
    name: "PACK_CLI_IMAGE_VERSION"
    type: "string"
  - description: "The name of the builder image to create."
    name: "BUILDER_IMAGE_NAME"
    type: "string"
  - default: "builder.toml"
    description: "The builder toml file to use for the pack builder create command."
    name: "PACK_BUILDER_TOML"
    type: "string"
  - default: []
    description: "The Arguments to be passed to the pack command."
    name: "PACK_CMD_FLAGS"
    type: "array"
  - default: "."
    description: "Directory containing the source files to build."
    name: "PACK_SOURCE_DIR"
    type: "string"
  steps:
  - args:
    - "builder"
    - "create"
    - "$(params.BUILDER_IMAGE_NAME)"
    - "--config"
    - "$(params.PACK_BUILDER_TOML)"
    - "$(params.PACK_CMD_FLAGS[*])"
    env:
    - name: "DOCKER_CONFIG"
      value: "$(workspaces.pack-workspace.path)/.docker"
    - name: "PACK_HOME"
      value: "$(workspaces.pack-workspace.path)"
    image: "$(params.PACK_CLI_IMAGE):$(params.PACK_CLI_IMAGE_VERSION)"
    name: "pack"
    workingDir: "$(workspaces.source-dir.path)/$(params.PACK_SOURCE_DIR)"
  workspaces:
  - name: "source-dir"
    optional: false
  - mountPath: "/workspace"
    name: "pack-workspace"
    optional: false
