package dev.snowdrop.service;

import dev.snowdrop.konflux.v1alpha1.Application;
import dev.snowdrop.konflux.v1alpha1.ApplicationBuilder;
import dev.snowdrop.konflux.v1alpha1.Component;
import dev.snowdrop.konflux.v1alpha1.ComponentBuilder;
import dev.snowdrop.model.Configurator;

import java.util.Map;
/*
New YAML example: https://github.com/konflux-ci/konflux-ci/blob/main/test/resources/demo-users/user/ns2/application-and-component.yaml

and

hereafter => YAML generated by konflux-ci
---
kind: Application
metadata:
  annotations:
    application.thumbnail: "10"
  name: my-quarkus
  namespace: user-ns1
spec:
  displayName: my-quarkus
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build", "bundle": "latest"}'
    image.redhat.com/image: '{"image":"quay.io/ch007m/user-ns1/my-quarkus/quarkus-1","visibility":"public","secret":"quarkus-1"}'
  finalizers:
  - test.appstudio.openshift.io/component
  - image-controller.appstudio.openshift.io/image-repository
  - image-registry-secret-sa-link.component.appstudio.openshift.io/finalizer
  - pac.component.appstudio.openshift.io/finalizer
  name: quarkus-1
  namespace: user-ns1
spec:
  application: my-quarkus
  componentName: quarkus-1
  resources: {}
  source:
    git:
      context: ./
      dockerfileUrl: src/main/docker/Dockerfile.jvm
      revision: main
      url: https://github.com/ch007m/new-quarkus-app-1.git
* */
public class ApplicationComponentBuilder {
    private final static String COMPONENT_ANNOTATION = "{\"visibility\":\"public\"}";

    public static Application createApplication(Configurator cfg) {
        Application application = new ApplicationBuilder()
            // @formatter:off
            .withNewMetadata()
               .withName(cfg.getJob().getName())
               .withAnnotations(Map.of("application.thumbnail","10"))
               .withNamespace(cfg.getNamespace())
            .endMetadata()
            .withNewSpec()
               .withDisplayName(cfg.getJob().getName())
            .endSpec()
            // @formatter:on
            .build();
        return application;
    }

    public static Component createComponent(Configurator cfg) {
        Component component = new ComponentBuilder()
            // @formatter:off
            .withNewMetadata()
                .withName(cfg.getJob().getName())
                .withNamespace(cfg.getNamespace())
                .withAnnotations(Map.of(
                    "build.appstudio.openshift.io/request","configure-pac",
                    "image.redhat.com/generate",COMPONENT_ANNOTATION
                ))
            .endMetadata()
            .withNewSpec()
               .withApplication(cfg.getJob().getName())
               .withComponentName(cfg.getJob().getName())
               .withNewSource()
                  .withNewGit()
                     .withUrl("TODO")
                     .withRevision("TODO")
                     .withContext("TODO")
                     .withDockerfileUrl("TODO")
                  .endGit()
               .endSource()
            .endSpec()
            // @formatter:on
            .build();
        return component;
    }
}
