---
apiVersion: "tekton.dev/v1"
kind: "PipelineRun"
metadata:
  annotations:
    tekton.dev/displayName: "Simple example of a Tekton pipeline echoing a message"
    tekton.dev/pipelines.minVersion: "0.60.x"
    tekton.dev/platforms: "linux/amd64"
  labels:
    app.kubernetes.io/version: "0.1"
  name: "simple-job-fetch-script"
spec:
  pipelineSpec:
    tasks:
    - name: "say-hello"
      taskSpec:
        steps:
        - image: "ubuntu"
          name: "run-script"
          script: |
            #!/usr/bin/env bash

            set -e
            echo "Say Hello"
