apiVersion: "tekton.dev/v1"
kind: "PipelineRun"
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: "0.60.x"
    tekton.dev/displayName: "Simple example of a Tekton pipeline including 2 actions\
      \ echoing Hello and Good bye when condition is met"
    tekton.dev/platforms: "linux/amd64"
  labels:
    app.kubernetes.io/version: "0.1"
  name: "simple-job-two-actions-when"
  namespace: "demo"
spec:
  params:
  - name: "message"
    value: "true"
  pipelineSpec:
    tasks:
    - name: "say-hello"
      taskSpec:
        steps:
        - image: "registry.access.redhat.com/ubi9@sha256:1ee4d8c50d14d9c9e9229d9a039d793fcbc9aa803806d194c957a397cf1d2b17"
          name: "run-script"
          script: |
            #!/usr/bin/env bash

            set -e
            echo "Say Hello"
    - name: "say-goodbye"
      runAfter:
      - "say-hello"
      taskSpec:
        steps:
        - image: "registry.access.redhat.com/ubi9@sha256:1ee4d8c50d14d9c9e9229d9a039d793fcbc9aa803806d194c957a397cf1d2b17"
          name: "run-script"
          script: |-
            #!/usr/bin/env bash

            set -e
            echo "and say Good bye to all of you !"
      when:
      - input: "$(params.message)"
        operator: "in"
        values:
        - "true"
  timeouts:
    pipeline: "300000000000ns"
