apiVersion: "tekton.dev/v1"
kind: "TaskRun"
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: "0.60.x"
    tekton.dev/displayName: "Simple example of a Tekton task echoing a message"
    tekton.dev/platforms: "linux/amd64"
  labels:
    app.kubernetes.io/version: "0.1"
  name: "simple-action-embedded-script"
spec:
  taskSpec:
    steps:
    - args:
      - "args"
      image: "registry.access.redhat.com/ubi9@sha256:1ee4d8c50d14d9c9e9229d9a039d793fcbc9aa803806d194c957a397cf1d2b17"
      name: "say-hello"
      script: |-
        #!/usr/bin/env bash

        set -e
        echo "Say Hello"
