name: Embed code in README

on:
  push:
    branches:
      - main

jobs:
  embed-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write # release changes require contents write
    steps:
      - uses: actions/checkout@v2

      - name: Markdown Code Embed
        uses: ippie52/markdown_code_embed_action@2.0.1