name: Embed code in README

on:
  push:
    branches:
      - main

jobs:
  embed-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write # release changes require contents write
    steps:
      - uses: actions/checkout@v3

      #- name: Markdown Code Embed
      #  uses: ippie52/markdown_code_embed_action@2.0.1
      #  with:
      #    args: '-b'

      - name: Markdown Code Embed
        run: |
          git clone https://github.com/ippie52/markdown_code_embed.git
          ./markdown_code_embed/mdce.py -f README.md
          cat README.md

      - name: Push the README file with snippet
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          
          set +e
          git add README.md
          git commit -m "README.md file augmented with snippet codes"
          git push