# Publish Pipelines generated when project is tagged
name: Publish Pipelines generated

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # release changes require contents write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run the builder application
        run: |
          java -jar target/quarkus-app/quarkus-run.jar -o generated -c configurations/tekton/simple-job-embedded-script-cfg.yaml

      - name: Check Pipeline generated
        run: |
          ls -la generated/

      - name: Push the README file with snippet
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

          set +e
          git add generated/*
          git commit -m "New \"pipelines\" yaml file(s) generated"
          git push